### ISSUE TITLE
32 bits loadable extension for windows?

### ISSUE THREAD

**Issue by bambax** [asg017/sqlite-http#28]
There is no pre-compiled 64 bits version of the command-line shell of SQLite for windows (AFAIK). On windows, one therefore has to use the 32 bits version (or build the 64 bits version).

But of course the 32 bits version won't load 64 bits extensions.

Would it therefore be possible to provide a 32 bits version of this extension as a windows dll?

Thank you and sorry for the trouble.

**Comment by asg017** [comment]
@bambax let me know if you're able to figure it out! I have successfully used the 64-bit windows version of nalgeon/sqlite with other sqlite extensions, so would love to see if there's anything else that can be improved.

**Comment by bambax** [comment]
I still can't load the extension. I can load and use all the extensions found on https://github.com/nalgeon/sqlean in the latest sqlite x64 on Windows, but for http0 I get `Error: %1 is not a valid win32 application`. @asg017 have you been able to test it successfully on Windows?

**Comment by bambax** [comment]
Also, compared to the extensions found on sqlean, the dlls for http0 and html0 are pretty huge... math.dll is only 67ko, crypto 112ko, wheras http0 is 15Mo or html0 12Mo...?
