### ISSUE TITLE
Unable to load into SQLite

### ISSUE THREAD

**Issue by ehonzik** [asg017/sqlite-http#33]
Unable to load into SQLite, tried on version 0.1.1 and 0.1.0 - Windows platform. SQLite version 3.45.1

`sqlite> .load ./http0`
`Error: The specified module could not be found.`

Module is in same folder as CLI. Any idea?

**Comment by Moaneschien** [comment]
```
SQLite version 3.45.0 2024-01-15 17:01:13 (UTF-16 console I/O)
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
sqlite> .load fastrand0
sqlite> .load html0
Error: The specified module could not be found.

sqlite> .load http0
Error: The specified module could not be found.

sqlite> .load jsonschema0
sqlite>
```

**Comment by twoxfh** [comment]
I think module could not be found is talking about sqlite3.dll. On my machine I run sqlite3.exe with sqlite3.dll in the same directory as http0.dll and I am able to .load http0.

**Comment by Moaneschien** [comment]
`sqlite3.dll`, `sqlite3.dll`, `sqlean.exe` and the libraries are all in the same directory. `fasrand0` loads, `html0` does not.

**Comment by little-brother** [comment]
The released `http0.dll` is a 64-bit library and it compiled by mingw64 and therefore requires `libwinpthread-1.dll` to work.
Sometimes there is only a 32-bit version of `libwinpthread-1.dll` in Windows and Windows tries to mix 32- and 64-bit libraries.

![изображение](https://github.com/user-attachments/assets/6825107d-d89c-4bf5-a5c8-a83d41eb071c)

The solutions are 
1. Build `http0.dll` with `-static` C-compiler flags to built-in `libwinpthread-1`
    ```
    go build -o http0.dll -buildmode=c-shared -ldflags="-s -w -extldflags=-static"
    ```
    `-s` and `-w` flags reduce a dll size by half.
2. Just put 64-bit [`libwinpthread-1.dll`](https://github.com/user-attachments/files/18140545/libwinpthread-1.zip) to an app folder.

**Comment by Moaneschien** [comment]
>     2. Just put 64-bit [`libwinpthread-1.dll`](https://github.com/user-attachments/files/18140545/libwinpthread-1.zip) to an app folder.

Worked flawless! Thanks little-brother.

**Comment by ehonzik** [comment]
@little-brother Works like a charm! Thanks...
